repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: check-merge-conflict
        name: Check for merge conflict strings
      - id: end-of-file-fixer
        name: Ensures that a file is either empty, or ends with one newline
      - id: check-json
        name: Linters for the json files in automation
      - id: check-yaml
        name: Linters for yaml files in automation
  - repo: 'https://github.com/shellcheck-py/shellcheck-py'
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        name: Linters for bash scripts used in automation
  - repo: 'https://github.com/PyCQA/bandit'
    rev: 1.7.2
    hooks:
      - id: bandit
        name: Checking for security impacts
