name: code standards

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Set up python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install python pkg resources
        run: sudo apt-get install --reinstall -y python-pkg-resources
      - name: Install setup tools
        run: pip install setuptools
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit on all the files
        run: pre-commit run --all-files
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
